model_name_or_path: /root/autodl-tmp/Qwen/Gemma
trust_remote_code: true
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
dataset: train_data_multi_50pct,merged_30pct
template: gemma
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4
output_dir: saves/gemma3-1b/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
lora_dropout: 0.05
val_size: 0.05
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 500
