model_name: "your-classifier-model"
seed: 42
train:
  batch_size: 32
  num_epochs: 5
  learning_rate: 1e-3
data:
  train_path: "data/train.jsonl"
  val_path: "data/val.jsonl"
  feature_fields: ["answers"]
save:
  output_dir: "checkpoints"
scoring:
  instrument: "PHQ-9"