model_name: "your-base-model"
seed: 42
train:
  batch_size: 16
  num_epochs: 3
  learning_rate: 3e-5
  grad_accum_steps: 1
  max_length: 1024
data:
  train_path: "data/train.jsonl"
  val_path: "data/val.jsonl"
  text_fields: ["user", "assistant"]
save:
  output_dir: "checkpoints"